import { createGlobalTheme, createGlobalThemeContract } from '@vanilla-extract/css'

const atomicVars = createGlobalThemeContract(
  {
    color: {
      commonWhite: null,
      commonBlack: null,
      purple900: null,
      purple800: null,
      purple700: null,
      purple600: null,
      purple500: null,
      purple300: null,
      purple100: null,
      purple50: null,
      neutral900: null,
      neutral700: null,
      neutral500: null,
      neutral300: null,
      neutral200: null,
      neutral100: null,
      neutral50: null,
      green700: null,
      green50: null,
      amber800: null,
      amber50: null,
      blue700: null,
      red700: null,
      red50: null,
    },
  },
  (_, path) => `color-atomic-${path.join('-')}`,
)

createGlobalTheme(':root', atomicVars, {
  color: {
    commonWhite: '#FFFFFF',
    commonBlack: '#17131A',
    purple900: '#2A0049',
    purple800: '#3A0065',
    purple700: '#4B0082',
    purple600: '#622398',
    purple500: '#7A46A8',
    purple300: '#B592CB',
    purple100: '#EEE6F4',
    purple50: '#F8F5FA',
    neutral900: '#211A25',
    neutral700: '#504657',
    neutral500: '#756B7B',
    neutral300: '#CFC7D3',
    neutral200: '#E4DEE7',
    neutral100: '#F3F0F5',
    neutral50: '#FAF9FB',
    green700: '#1B6B4A',
    green50: '#E7F5EE',
    amber800: '#815500',
    amber50: '#FFF6DF',
    blue700: '#1D4ED8',
    red700: '#B42318',
    red50: '#FEF3F2',
  },
})

export const semanticVars = createGlobalThemeContract(
  {
    color: {
      background: null,
      surface: null,
      surfaceMuted: null,
      surfaceRaised: null,
      labelNormal: null,
      labelStrong: null,
      labelNeutral: null,
      labelMuted: null,
      lineNormal: null,
      lineStrong: null,
      primaryNormal: null,
      primaryMuted: null,
      primaryStrong: null,
      primaryHeavy: null,
      primarySoft: null,
      primarySubtle: null,
      onPrimary: null,
      positive: null,
      positiveSoft: null,
      warning: null,
      warningSoft: null,
      negative: null,
      negativeSoft: null,
      weekendSaturday: null,
      weekendSunday: null,
    },
    font: {
      family: null,
      size: {
        display: null,
        titleLarge: null,
        titleMedium: null,
        titleSmall: null,
        headingLarge: null,
        headingMedium: null,
        headingSmall: null,
        bodyLarge: null,
        bodyMedium: null,
        bodySmall: null,
        labelLarge: null,
        labelMedium: null,
        labelSmall: null,
        captionLarge: null,
        captionSmall: null,
        numberLarge: null,
        numberMedium: null,
        numberSmall: null,
      },
      weight: {
        regular: null,
        medium: null,
        semibold: null,
        bold: null,
        extraBold: null,
      },
      lineHeight: {
        tight: null,
        normal: null,
        relaxed: null,
      },
      letterSpacing: {
        tight: null,
        normal: null,
      },
    },
  },
  (_, path) =>
    path[0] === 'color'
      ? `color-semantic-${path.slice(1).join('-')}`
      : `font-semantic-${path.slice(1).join('-')}`,
)

createGlobalTheme(':root', semanticVars, {
  color: {
    background: atomicVars.color.commonWhite,
    surface: atomicVars.color.commonWhite,
    surfaceMuted: atomicVars.color.purple50,
    surfaceRaised: atomicVars.color.neutral50,
    labelNormal: atomicVars.color.neutral900,
    labelStrong: atomicVars.color.commonBlack,
    labelNeutral: atomicVars.color.neutral700,
    labelMuted: atomicVars.color.neutral500,
    lineNormal: atomicVars.color.neutral200,
    lineStrong: atomicVars.color.neutral300,
    primaryNormal: atomicVars.color.purple700,
    primaryMuted: atomicVars.color.purple600,
    primaryStrong: atomicVars.color.purple800,
    primaryHeavy: atomicVars.color.purple900,
    primarySoft: atomicVars.color.purple100,
    primarySubtle: atomicVars.color.purple50,
    onPrimary: atomicVars.color.commonWhite,
    positive: atomicVars.color.green700,
    positiveSoft: atomicVars.color.green50,
    warning: atomicVars.color.amber800,
    warningSoft: atomicVars.color.amber50,
    negative: atomicVars.color.red700,
    negativeSoft: atomicVars.color.red50,
    weekendSaturday: atomicVars.color.blue700,
    weekendSunday: atomicVars.color.red700,
  },
  font: {
    family:
      "'Pretendard JP', 'Pretendard', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    size: {
      display: '2.5rem',
      titleLarge: '2rem',
      titleMedium: '1.75rem',
      titleSmall: '1.5rem',
      headingLarge: '1.375rem',
      headingMedium: '1.25rem',
      headingSmall: '1.125rem',
      bodyLarge: '1rem',
      bodyMedium: '0.9375rem',
      bodySmall: '0.875rem',
      labelLarge: '0.9375rem',
      labelMedium: '0.875rem',
      labelSmall: '0.75rem',
      captionLarge: '0.8125rem',
      captionSmall: '0.75rem',
      numberLarge: '2rem',
      numberMedium: '1.5rem',
      numberSmall: '1rem',
    },
    weight: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extraBold: '800',
    },
    lineHeight: {
      tight: '1.25',
      normal: '1.5',
      relaxed: '1.6',
    },
    letterSpacing: {
      tight: '-0.02em',
      normal: '0',
    },
  },
})
